mysql:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=dbpass
   - MYSQL_DATABASE=testdb
auth-service:
  image: zigoo/auth-service
  ports:
   - 8181:8181
  links:
   - mysql
   - discovery-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
discovery-service:
  image: zigoo/discovery-service
  ports:
   - 8761:8761
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
gateway-service:
  image: zigoo/gateway-service
  ports:
   - 9999:9999
  links:
   - auth-service
   - discovery-service
   - account-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
account-service:
  image: zigoo/account-service
  links:
   - auth-service
   - discovery-service
   - mysql
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
online-ui1-service:
  image: zigoo/online-ui1-service
  ports:
   - 8781:8781
  links:
   - discovery-service
   - account-service
   - auth-service
   - gateway-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
online-ui2-service:
  image: zigoo/online-ui2-service
  ports:
   - 8782:8782
  links:
   - discovery-service
   - account-service
   - auth-service
   - gateway-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP       
   